### ISSUE TITLE
Need to use in dart <2.10 so is there any way to do it?

### ISSUE THREAD

**Issue by a1111198** [Maksimka101/app_install_date#1]
I am using flutter 1.23. with one of my old projects due to very high dependency complications I can't switch to another so can you please help me that how can I configure it in dart<2.10?

**Comment by Maksimka101** [comment]
Hi, Akash.

You can fork this package and move it to the flutter 1.23 and dart 2.9. I can't imagine another way to solve your problem :)

**Comment by a1111198** [comment]
If possible can you please do it and commit so that I can directly
integrate it with my project and many other like me.

**Comment by Maksimka101** [comment]
No, I can't do it, sorry

However it's easy and you can try to do it by yourself.

**Comment by a1111198** [comment]
Ok, thanks for the reply.
